CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) DEFAULT 'USER'
);


CREATE TABLE IF NOT EXISTS games (
    id SERIAL PRIMARY KEY,
    player_id INT NOT NULL,
    player_score INT NOT NULL,
    game_status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    game_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_game_player FOREIGN KEY (player_id) REFERENCES users(id) ON DELETE CASCADE
);
